baseURL = "https://casualrp.com"
languageCode = "en-us"
title = "Casual RP"
theme = "podcast"
HUGO_ENV = "development" # "production"
googleAnalytics = "UA-115767677-1"

[author]
  name = "Sean Stanley"
  company = "Redhead Web"
  email = "casualrp.podcast@gmail.com"

[params]
  podcastImage = "https://res.cloudinary.com/casualrp/image/upload/v1520396126/casualRP-2.png"
  audioRootURL = "http://podcast.casualrp.com"
  barsColor = "#5E9B42"
  description = "A Boy, Guard, Thief and Giant are caught between the wild cries of the jungle and the hammers of industry… this is Casual RP. A 5th edition Dungeons and Dragons Actual Play Podcast"
  subtitle = "A Boy, Guard, Thief and Giant are caught between the wild cries of the jungle and the hammers of industry… this is Casual RP. A 5th edition Dungeons and Dragons Actual Play Podcast"
  summary = "Twice-weekly actual play DnD podcast done by complete amateurs. We have a gritty and realistic medieval setting to explore where the plot and quests are shaped by the players and listeners."
  itunesLink = "https://itunes.apple.com/us/podcast/id1352749733"
  stitcherLink = "https://www.stitcher.com/podcast/casual-rp"
  # Social Media Links
  twitch = "https://twitch.tv/casualrp"
  facebook = "https://www.facebook.com/casualrp.podcast/"
  twitter = "https://twitter.com/casualrp"
  instagram = "https://www.instagram.com/casualrp.podcast/"
  googleSiteVerification = "W9oT3nQgViF8PO9W8uH7CvPdiSWuENIQKEUdHugqhDM"

[[menu.main]]
  name = "Wiki / Lore"
  weight = -109
  identifier = "wiki-lore"
  url = "http://therealmsofkelmarth.wikia.com/wiki/The_Jungle_Campaign"

[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about"

[[menu.main]]
  name = "Contact"
  weight = 1
  identifier = "contact"
  url = "/contact"


[imaging]
  # Default resample filter used for resizing. Default is Box,
  # a simple and fast averaging filter appropriate for downscaling.
  # See https://github.com/disintegration/imaging
  resampleFilter = "box"

  # Defatult JPEG quality setting. Default is 75.
  quality = 75

  # Anchor used when cropping pictures.
  # Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
  # Smart Cropping is content aware and tries to find the best crop for each image.
  # Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
  anchor = "smart"
