baseURL = "http://casualrp.com"
languageCode = "en-us"
title = "Casual RP Podcast"
theme = "podcast"
HUGO_ENV = "development" # "production"
googleAnalytics = "UA-115767677-1"
buildFuture = true
disableKinds = [
  "home",
  "taxonomy",
  "taxonomyTerm",
  "404",
]

[author]
  name = "Sean Stanley"
  company = "Redhead Web"
  email = "casualrp.podcast@gmail.com"

[params]
  podcastImage = "http://res.cloudinary.com/casualrp/image/upload/v1520396126/casualRP-2.png"
  audioRootURL = "http://podcast.casualrp.com"
  barsColor = "#5E9B42"
  description = "A Boy, Guard, Thief and Giant are caught between the wild cries of the jungle and the hammers of industry… this is Casual RP. A 5th edition Dungeons and Dragons Actual Play Podcast"
  subtitle = "A Boy, Guard, Thief and Giant are caught between the wild cries of the jungle and the hammers of industry… this is Casual RP. A 5th edition Dungeons and Dragons Actual Play Podcast"
  summary = "Twice-weekly actual play DnD podcast done by complete amateurs. We have a gritty and realistic medieval setting to explore where the plot and quests are shaped by the players and listeners."
  itunesLink = "https://itunes.apple.com/us/podcast/id1352749733"
  stitcherLink = "https://www.stitcher.com/podcast/casual-rp"
  # Social Media Links
  facebook = "https://www.facebook.com/casualrp.podcast/"
  twitter = "https://twitter.com/casualrp"
  instagram = "https://www.instagram.com/casualrp.podcast/"
  googleSiteVerification = "W9oT3nQgViF8PO9W8uH7CvPdiSWuENIQKEUdHugqhDM"
